/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ht3cjamDQZq
 */
"use client";
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { FormEvent } from "react";
import { useRouter } from 'next/navigation';

function Header() {
  const router = useRouter();
  const filter = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
  };
  const logout = () => {
    router.push('/');
  };
  return (
    <div className="flex flex-col h-full min-h-0">
      <div className="flex h-14 items-center border-b bg-gray-100 px-4 md:px-6 dark:bg-gray-800">
        <div className="flex items-center gap-2 mr-4 shrink-0">
          <div className="flex items-center h-8 w-8 rounded-full bg-gray-200 dark:bg-gray-900">
          </div>
          <Link className="font-bold hidden md:flex text-base dark:text-gray-50" href="#">
            TIES
          </Link>
        </div>
        <form onSubmit={filter} role="search" className="flex-1 min-w-0">
          <div className="mx-4 w-full max-w-md" style={{position: 'relative'}}>
            <Input
              aria-label="Search"
              className="bg-white shadow-none appearance-none pl-8 peer-rtl:pr-8 peer-rtl:pl-3"
              placeholder="Search"
              type="search"
            />
            <Button style={{
                  position: 'absolute',
                  left: '410px'
              }} className="absolute inset-y-0 flex items-center pl-3 pointer-events-none">
              <SearchIcon className="h-4 w-4 text-gray-400 dark:text-gray-500" />
            </Button>
          </div>
        </form>
        <div className="flex items-center ml-auto gap-4">
          <div className="flex items-center gap-2">
            <div className="font-semibold">{typeof window !== 'undefined' && window.sessionStorage.getItem('username')}</div>
          </div>
          <Button onClick={logout} size="icon" variant="ghost">
            <LogOutIcon className="w-4 h-4" />
            <span className="sr-only">Logout</span>
          </Button>
        </div>
      </div>
    </div>
  )
}


function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function LogOutIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  )
}


export default Header;
